create table CUSTOMER (
	CUSTOMER_ID SERIAL primary key,
	FIRST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	ADDRESS VARCHAR(150),
	BILLING_INFO VARCHAR(150)
);

create table MOVIES (
	MOVIE_ID SERIAL primary key,
	MOMVIE_TITLE VARCHAR(250),
	MOVIE_RUNTIME VARCHAR(50),
	MOVIE_RATING VARCHAR(20)
);

create table TICKETS (
	TICKET_ID SERIAL primary key,
	TICKET_COST NUMERIC(4,2),
	TICKET_AMOUNT INTEGER,
	TOTAL_TICKET_COST NUMERIC(8,2),
	MOVIE_ID INTEGER,
	foreign key(MOVIE_ID) references MOVIES(MOVIE_ID)
);

create table CONCESSIONS (
	CONCESSIONS_ID SERIAL primary key,
	CONCESSIONS_ITEMS VARCHAR(200),
	CONCESSIONS_TOTAL NUMERIC(10,2),
	CUSTOMER_ID INTEGER,
	foreign key(CUSTOMER_ID) references CUSTOMER(CUSTOMER_ID)
);


alter table MOVIES RENAME column MOMVIE_TITLE TO MOVIE_TITLE;
alter table TICKETS add column CUSTOMER_ID INTEGER;
alter table TICKETS add foreign key(CUSTOMER_ID) references CUSTOMER(CUSTOMER_ID);